//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приложение_для_курсовой.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-NIKISIN\\JET;Initial Catalog=\"Онлайн-магазин настольных игр\";U" +
            "ser ID=sa;Password=Q1w2e3r4")]
        public string Онлайн_магазин_настольных_игрConnectionString {
            get {
                return ((string)(this["Онлайн_магазин_настольных_игрConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ETERNAL\\NIKISIN;Initial Catalog=\"Онлайн-магазин настольных игр\";User " +
            "ID=sa;Password=Q1w2e3r4")]
        public string Онлайн_магазин_настольных_игрConnection {
            get {
                return ((string)(this["Онлайн_магазин_настольных_игрConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-NIKISIN\\JET;Initial Catalog=\"Онлайн-магазин настольных игр\";I" +
            "ntegrated Security=True")]
        public string Онлайн_магазин_настольных_игрConnectionString1 {
            get {
                return ((string)(this["Онлайн_магазин_настольных_игрConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-NIKISIN\\JET;Initial Catalog=Онлайн-магазин;User ID=sa;Passwor" +
            "d=Q1w2e3r4")]
        public string Онлайн_магазинConnectionString {
            get {
                return ((string)(this["Онлайн_магазинConnectionString"]));
            }
        }
    }
}
